apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: class-exercise
spec:
  type: ClusterIP
  selector:
    tier: backend
  ports:
    - port: 5001
      targetPort: 5001
      # nodePort: 30304 #30K-32.7K
  