apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: class-exercise
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30303 #30K-32.7K
  